name: num2

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
  
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Set up Git
      run: |
        git config --global user.name "mirzakurtovic"
        git config --global user.email "mirzakurtovic0@gmail.com"

    - name: git
      run: git remote add origin https://github.com/mirzakurtovic/mirzakurtovic1.github.io.git

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Run the tests
      run: npm test

    - name: Build
      run: npm run build
      
    - name: Deploy
      run: npm run deploy
